# AdGuardHome api configuration
api:
  host: adguard.example.com
  port: 80
  proto: http
  username: admin
  passwd: admin
  startup: True

# Configuration of ping jobs
ping_jobs:
  # full configuration
  - job:
      domain: server.lan
      interval: 60
      count: 4
      timeout: 2
      answers:
        - 10.0.0.1
        - 10.0.0.2
        - 10.0.0.3

  # configuration using default options
  - job:
      domain: server2.lan
      answers:
        - 10.0.1.1
        - 10.0.1.2
        - 10.0.1.3

# configuration of http jobs
http_jobs:
  - job:
      domain: example.lan
      interval: 10
      status: 200
      port: 80
      proto: http
      answers:
        - 10.0.2.1
        - 10.0.2.2

# configuration of static entry jobs
static_entry:
  - job:
      domain: router.lan
      answer: 192.168.1.1
      interval: 60